# Generated by Django 5.2.15 on 2026-06-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="provider",
            new_name="providers_p_special_3d9b16_idx",
            old_name="providers_p_special_54f75d_idx",
        ),
        migrations.RenameIndex(
            model_name="provider",
            new_name="providers_p_is_veri_f6c3b8_idx",
            old_name="providers_p_is_veri_58ffbf_idx",
        ),
    ]
