# Generated by Django 5.2.17 on 2026-08-11 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        (
            "providers",
            "0002_rename_providers_p_special_54f75d_idx_providers_p_special_3d9b16_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_provider_appointment_slot",
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("provider", "appointment_date", "appointment_time"),
                name="unique_active_provider_appointment_slot",
            ),
        ),
    ]
