# Generated by Django 5.2.17 on 2026-08-12 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_remove_appointment_unique_provider_appointment_slot_and_more",
        ),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="appointment_scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic"),
                    ("APPOINTMENT_REMINDER", "Appointment reminder"),
                ],
                default="GENERIC",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "APPOINTMENT_REMINDER")),
                fields=("appointment", "appointment_scheduled_for"),
                name="unique_appointment_reminder_schedule",
            ),
        ),
    ]
